### ISSUE TITLE
动态表单存储及拓展

### ISSUE THREAD

**Issue by JerryWen1994** [GDJiaMi/researching#2]
消防项目中使用的动态表单技术沉淀及拓展
- 如何实现动态表单
- 动态表单的验证过程
- 表单项之间的互动
- 表单验证失败后focus到对应的表单项

**Comment by ivan-94** [comment]
需要提到这几点：

- 实现动态表单的前提是这些表单有统一的接口或协议
- 组件如何设计
- 表单和预览结构是统一的，组件应该怎么设计？
- 考虑性能问题。这里可以扩展一下，研究一下如何使用React的开发工具去确定性能问题

**Comment by JerryWen1994** [comment]
动态表单思维导图
![image](https://user-images.githubusercontent.com/20969011/59730660-cd050d00-9275-11e9-86b6-d3ed908b18a7.png)

**Comment by JerryWen1994** [comment]
![image](https://user-images.githubusercontent.com/20969011/59810628-ca1f2080-9338-11e9-9105-84b417eb0e67.png)
