### ISSUE TITLE
从preact中学习react的基本原理

### ISSUE THREAD

**Issue by ivan-94** [GDJiaMi/researching#5]
-  diff基本算法
- hook基本原理

**Comment by Hzyhhh** [comment]
![0618批注记录10-12-36](https://user-images.githubusercontent.com/25975853/59654788-5828c900-91ca-11e9-87f8-426419f50ae8.jpg)
![0618批注记录10-19-09](https://user-images.githubusercontent.com/25975853/59654935-f583fd00-91ca-11e9-86d9-de08697cc7c6.jpg)
**Virtual-DOM形成过程**

**Comment by Hzyhhh** [comment]
![0618批注记录10-23-15](https://user-images.githubusercontent.com/25975853/59655110-c7eb8380-91cb-11e9-8168-435da9d05ea0.jpg)
**ReactDOM的转换过程**

**Comment by Hzyhhh** [comment]
![0618批注记录10-40-52](https://user-images.githubusercontent.com/25975853/59655243-3cbebd80-91cc-11e9-8517-89145b5506c0.jpg)
**Virtual-DOM的更新机制**

**Comment by Hzyhhh** [comment]
![0618批注记录11-00-19](https://user-images.githubusercontent.com/25975853/59655318-71cb1000-91cc-11e9-9c21-c01f0d1d0a96.jpg)
![0618批注记录11-08-44](https://user-images.githubusercontent.com/25975853/59655321-74c60080-91cc-11e9-859c-fec62dbb2e82.jpg)
**Hooks useState的原理及实现过程**

**Comment by Hzyhhh** [comment]
[[技术地图] 从Preact中了解组件和hooks基本原理](https://juejin.im/post/5cfa29e151882539c33e4f5e#heading-0)
