### ISSUE TITLE
前端性能监控，埋点

### ISSUE THREAD

**Issue by JerryWen1994** [GDJiaMi/researching#7]
接下来的专题研究是前端性能监控，埋点
- 什么是前端性能监控与埋点
- 为什么需要进行埋点
- 如何做到前端埋点

**Comment by ivan-94** [comment]
埋点只是前端的一部分，还有数据的收集，分析和监控服务

**Comment by 597796340** [comment]
前端埋点应该指的是数据的采集，而数据分析是前端采集信息后进行分析处理，并将用户行为信息进行深层次的拓展，如分析用户行为信息后，可新增其他功能模块，或者针对性的对前端进行优化处理

**Comment by JerryWen1994** [comment]
> 埋点只是前端的一部分，还有数据的收集，分析和监控服务

前端埋点应该指的是数据的采集，而数据分析是前端采集信息后进行分析处理，并将用户行为信息进行深层次的拓展，如分析用户行为信息后，可新增其他功能模块，或者针对性的对前端进行优化处理
